service: serverless-lambda-s3

provider:
  name: aws
  runtime: nodejs14.x
  stage: production
  deploymentBucket:
    name: serverless-lambda-s3-deployment-bucket-${opt:stage, self:provider.stage}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:*
      Resource: '*'

plugins:
  - serverless-webpack
  - serverless-deployment-bucket

custom:
  webpack:
    webpackConfig: webpack.config.js
    includeModules: true

functions:
  processCSV:
    name: processCSV
    handler: src/handler.processCSV
    events:
      - s3:
          bucket: CSV-BUCKET-NAME-CHANGE-ME
          event: s3:ObjectCreated:*
          rules:
            - suffix: .csv
    environment:
      FIXED_WIDTH_BUCKET: ${self:resources.Resources.fixedwidth.Properties.BucketName}
      NODE_ENV: production

resources:
  Resources:
    fixedwidth:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: FIXED-WIDTH-BUCKET-NAME-CHANGE-ME
