service: serverless-lambda-s3

provider:
  name: aws
  runtime: nodejs14.x
  stage: production
  deploymentBucket:
    name: serverless-lambda-s3-deployment-bucket-${opt:stage, self:provider.stage}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:*
      Resource: '*'

plugins:
  - serverless-webpack
  - serverless-deployment-bucket

custom:
  webpack:
    webpackConfig: webpack.config.js
    includeModules: true
    packagerOptions:
      scripts:
        # sharp module needs to rebuild for lambda
        - npm rebuild --arch=x64 --platform=linux --target=14.20.1 sharp
functions:
  s3NewObjectResizeHandler:
    name: s3NewObjectResizeHandler
    handler: ./src/imageResize.handler
    events:
      - s3:
          bucket: s3-image-resizer-bucket-source
          event: s3:ObjectCreated:*
          existing: true
          forceDeploy: true
    environment:
      TARGET_BUCKET: s3-image-resizer-bucket-target
