service: serverless-lambda-s3

provider:
  name: aws
  runtime: nodejs14.x
  stage: production
  deploymentBucket:
    name: serverless-lambda-s3-deployment-bucket-${opt:stage, self:provider.stage}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:*
      Resource: '*'

plugins:
  - serverless-webpack
  - serverless-deployment-bucket

custom:
  webpack:
    webpackConfig: webpack.config.js
    includeModules: true
    packagerOptions:
      scripts:
        # sharp module needs to rebuild for lambda
        - npm rebuild --arch=x64 --platform=linux --target=14.20.1 sharp
functions:
  s3NewObjectResizeHandler:
    name: s3NewObjectResizeHandler
    handler: ./src/imageResize.handler
    events:
      - s3:
          bucket: SOURCE-BUCKET-NAME-CHANGE-ME
          event: s3:ObjectCreated:*
    environment:
      TARGET_BUCKET: ${self:resources.Resources.resizedS3.Properties.BucketName}

resources:
  Resources:
    resizedS3:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: RESIZE-BUCKET-NAME-CHANGE-ME
